<section class="wrapper box-fluid">
    <!--style="margin-top: 90px;" En la portada aparace un spacion-->
    <div class="container">
        <?php echo $this->render('application/payment/order/header'); ?> 
        <form method="post"  class="frm form-horizontal form_left_text" id="formPagos">
            <div class="row" style="margin-top: 80px;">
                <div class="col-md-6">
                    <div class="data_pagos border_form text_align_form">
                        <div class="bgGrisDark pTitleSub text-center mayus blanco border_out"><span class="iLeft border_in">1</span> <strong>Datos de pago</strong></div>
                        <div class="bgBlanco cnt_form">
                            <input type="hidden" id="txtTips_id" value="">
                            <div class="form-group">
                                <label for="nombres" class="col-md-4 control-label">Nombres <span class="red">*</span></label>
                                <div class="col-md-8">
                                    <?php echo $this->formRow($this->formPagos->get("nombres")); ?>
                                </div>
                            </div>
                            <div class="form-group">
                                <label for="nombres" class="col-md-4 control-label">Apellidos <span class="red">*</span></label>
                                <div class="col-md-8">
                                    <?php echo $this->formRow($this->formPagos->get("apellidos")); ?>
                                </div>
                            </div>
                            <div class="form-group">
                                <label for="email" class="col-md-4 control-label">Email <span class="red">*</span></label>
                                <div class="col-md-8">
                                    <?php echo $this->formRow($this->formPagos->get("email")); ?>
                                </div>
                            </div>
                            <div class="form-group">
                                <label for="countries" class="col-md-4 control-label">País <span class="red">*</span></label>
                                <div class="col-md-8">
                                    <?php echo $this->formRow($this->formPagos->get("countries")); ?>
                                    <input type="hidden" name="codepe" value="<?php echo $this->partnerdata['partner_id'] ?>" />
                                </div>
                            </div>
                            <div class="form-group">
                                <label for="ciudad" class="col-md-4 control-label">Ciudad</label>
                                <div class="col-md-8">
                                    <?php echo $this->formRow($this->formPagos->get("ciudad")); ?>
                                </div>
                            </div>
                            <div class="form-group">
                                <label for="direccion" class="col-md-4 control-label">Dirección</label>
                                <div class="col-md-8">
                                    <?php echo $this->formRow($this->formPagos->get("direccion")); ?>
                                </div>
                            </div>
                            <span><span class="red">*</span><small> Campos obligatorios</small></span>
                        </div>
                    </div>
                    <div class="detalles_pagos border_form text_align_form">
                        <div class="bgGrisDark pTitleSub text-center mayus blanco border_out"><span class="iLeft border_in">2</span> <strong>Detalles</strong></div>
                        <div class="bgBlanco cnt_form">
                            <div class="form-group">
                                <div class="col-md-12">
                                    <span class="one_biia">Total: $</span><span class="two_biia"><?php echo $this->total['total']; ?></span>
                                </div>
                            </div>

                            <?php if (!empty($this->items)): ?>
                                <?php foreach ($this->items as $value): ?>
                                    <div>

                                        <div class="form-group">
                                            <div class="col-md-12">
                                                <span class="one_biia">Producto: </span><span class="two_biia"><?php echo $value['name']; ?></span>
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            <div class="col-md-12">
                                                <span class="one_biia">Beneficios:</span>
                                                <span class="two_biia"><?php echo $value['options']['description']; ?></span>
                                            </div>
                                        </div>

                                    </div>
                                <?php endforeach ?>
                            <?php endif ?>

                        </div>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="metodo_pay text_align_form border_form">
                        <div class="bgGrisDark pTitleSub text-center mayus blanco border_out"><span class="iLeft border_in">3</span> <strong>Seleccione la forma de pago</strong></div>
                        <div class="bgBlanco cnt_form">
                            <div class="list_card">
                                <ul id="idImagesPay">
                                </ul>
                            </div>
                            <div class="form-group">
                                <label for="ciudad" class="col-md-4 control-label">Tipo de pago</label>
                                <div class="col-md-8">
                                    <select id="cbxPayment" class="form-control cb_type_card" name="typecard">
                                        <option value="">Seleccionar</option>
                                    </select>
                                </div>
                            </div>
                            <div class="form-group">
                                <label for="ciudad" class="col-md-4 control-label">Número de tarjeta</label>
                                <div class="col-md-8">
                                    <?php echo $this->formRow($this->formPagos->get("numberCard")); ?>
                                </div>
                            </div>
                            <div class="form-group">
                                <label for="ciudad" class="col-md-4 control-label">Fecha caducidad</label>
                                <div class="col-md-8">
                                    <div class="row">
                                        <div class="col-md-4"><?php echo $this->formRow($this->formPagos->get("month")); ?></div>
                                        <div class="col-md-4"><?php echo $this->formRow($this->formPagos->get("year")); ?></div>
                                    </div>
                                </div>
                            </div>
                            <div class="form-group">
                                <label for="ciudad" class="col-md-4 control-label">CVC</label>
                                <div class="col-md-4">
                                    <?php echo $this->formRow($this->formPagos->get("ccv")); ?>
                                </div>
                                <div class="col-md-4">
                                    <a href="#cvc" data-toggle="modal" data-target="#modalCVC" class="lh2">¿Qué es el CVC? <i class="fa fa-credit-card"></i></a>
                                </div>
                            </div>
                            <p class="text-center"><button tabindex="10" type="submit" class="btn btn-lg bNaranja mayus btn_pay" id="btnPagar">Pagar ahora</button></p>
                            <p class="text-center"><span class="glyphicon glyphicon-lock" aria-hidden="true"></span> Conexión segura</p>
                            <p class="text-center"><img src="https://www.instantssl.com/images/comodo-secure-padlock.png" width="100px"></p>
                        </div>
                    </div>
                </div><!-- end content -->
            </div>
        </form>

        <!-- Modal -->
        <div id="modalPay" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
            <div class="modal-dialog modal-lg">
                <button type="button" class="close close_span" data-dismiss="modal"><span aria-hidden="true">&times;</span></button>
                <div class="modal-content">
                    <iframe id="frame" src="" width="100%" height="870px"></iframe>
                </div>
            </div>
        </div>

        <div class="modal fade" id="modalCVC" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                        <h4 class="modal-title" id="myModalLabel">Código de seguridad al reverso de tu tarjeta</h4>
                    </div>
                    <div class="modal-body">
                        <p class="text-center"><img src="<?php echo $this->server('static') ?>s/img/cvv2.jpg" alt="CVC"></p>
                    </div>
                </div>
            </div>
        </div>

        <div class="modal fade" id="modalDepositos" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                        <h4 class="modal-title" id="myModalLabel">DEPÓSITOS Y TRANSFERENCIAS</h4>
                    </div>
                    <div class="modal-body">

                        <div class="fauq">
                            <div class="central">

                                <div class="usuaria">
                                    <ul class="datae">
                                        <li>Toma los datos de la Cta. Bancaria asignados a LIMA, PERÚ:</li>
                                        <li>Datos del Titular:</li>
                                        <li>Banco: Scotiabank Perú SAA</li>
                                        <li>Titular: BIIA LAB</li>
                                        <li>Cuenta Dolares 000-4454339 (CCI:009-220-000004454339-55) </li>
                                        <li>SWIFT: BSUDPEPL</li>
                                        <li>Dirección del banco: Av. Juan de Arona Nro. 809,</li>
                                        <li>San Isidro, Lima &ndash; Peru</li>
                                    </ul>
                                </div>
                                <div class="row panel">
                                    <div class="col-md-2 text-center"><img alt="" src="http://biialab.org/assets/images/icon2_.png"></div>
                                    <div class="col-md-10">Realiza el deposito o transferencia por el valor exacto en dólares o en pesos de tu país al cambio oficial.</div>
                                </div>
                                <div class="row panel">
                                    <div class="col-md-2 text-center"><img alt="" src="http://biialab.org/assets/images/icon1_.png"></div>
                                    <div class="col-md-10">Envía un mail a la siguiente dirección: lapineda@biialab.org</div>
                                </div>
                                <div class="row panel">
                                    <div class="col-md-2 text-center"><img alt="" src="http://biialab.org/assets/images/icon3_.png"></div>
                                    <div class="col-md-10">El mismo debe tener como asunto del correo: CURSO BIIA LAB y en el cuerpo detallar tus datos, (Nombres y Apellidos, Nro. Documento Nacional de Identidad (D.N.I.) y Fecha de nacimiento)</div>
                                </div>

                            </div>
                        </div>

                    </div>
                </div>
            </div>
        </div>

        <div class="modal fade" id="modalWU" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                        <h4 class="modal-title" id="myModalLabel">PAGOS POR WESTER UNION</h4>
                    </div>
                    <div class="modal-body">

                        <p>Usted podrá realizar sus pagos desde un agente Western Union, debido a que cuenta con agencias en todo el mundo Ud. tiene en su ciudad una agencia muy cerca.</p>
                        <p><a href="http://locations.westernunion.com/?locale=es" target="_blank" title="Busca tu agente western union más cercano - Click Aquí">Busca tu agente western union más cercano</a></p>

                        <ol>
                            <li>Dirijasé a la agencia de Western Union más cercana con su Cédula de Identidad original.</li>
                            <li>Complete el formulario con sus datos y los del Receptor del Envío del dinero y entrégueselo al Agente con el dinero en efectivo y firme el recibo.</li>
                            <li><p><strong>Datos del Receptor:</strong><br />
                                    Nombre: Biia LAB<br />
                                    NIT: 900-776.386-2<br />
                                    Dirección: Crda. 49 B 93 88, La Castellana<br />
                                    Ciudad: Bogotá<br />
                                    País: Colombia<br />
                                    Teléfono: +57 8051890 – Ext. 105<br /></p>
                            </li>
                            <li>Asegúrese de pedir su recibo donde figura su Número de Control de Envío de Dinero (MTCN) que le permitirá conocer el estado del envío de dinero por teléfono o en línea.</li>
                            <li>Escriba un correo a admin@biialab.org con los siguientes datos para que nosotros podamos recibir su envío de dinero y gestionar su ticket.
                                <ul>
                                    <li>Asunto del correo: PAGO CURSO NOEUROMARKETING</li>
                                    <li>Fecha del envío y País de procedencia del envío.</li>
                                    <li>Nombre completo de quién hizo el envío de dinero. (REMITENTE)</li>
                                    <li>Número del comprobante que te entrega Western Union (MTCN)</li>
                                    <li>Cantidad de dinero depositada en dólares (US$)</li>
                                </ul>
                            </li>
                        </ol><br />

                        <p>El proceso de pago con Western Union es rápido y la activación de los servicios se realizan dentro de las 24 horas después de reportado el pago.</p>

                        <p><strong>MUY IMPORTANTE:</strong><br />
                            En el mensaje debes ENVIAR ESCANEADO el FORMULARIO que te entrega Western Union como COMPROBANTE DE PAGO.</p>

                        <p><strong>NOTA:</strong> En ciertas ocaciones puede demorar HASTA 72 HORAS HABILES, desde el momento en que has hecho el envío hasta poder recibirlo.</p>

                        <p><strong>AVERIGÜE LOS COSTOS DE COMISIONES QUE FIJA WESTERN UNION POR EL ENVIO DE DINERO.</strong></p>

                    </div>
                </div>
            </div>
        </div>
        <?php echo $this->render('application/payment/order/footer'); ?> 
    </div>
</section>    
<?php echo $this->headLink()->prependStylesheet($this->server('static') . 's/css/jquery.alerts.css'); ?>
<?php echo $this->headScript()->prependFile($this->server('static') . 's/js/jquery.alerts.js'); ?>
<script>
    og.formaPago = 'CC';
    $(document).ready(function () {
        //$("#tabs").tabs();
        og.createOption(<?php echo $this->optionPayment ?>);
        $("#tabs").tabs({
            beforeActivate: function (event, ui) {
                var idTab = ui.newPanel.attr('id')
                if (idTab == 'tabs-1') {
                    og.formaPago = 'CC';
                }
                if (idTab == 'tabs-2') {
                    og.formaPago = 'PE';
                }
            }
        });

        $("#formPagos").validate({
            rules: {
                nombres: {
                    required: true
                },
                email: {
                    required: true,
                    email: true
                },
                countries: {
                    required: true
                },
                ciudad: {
                    required: true
                },
                direccion: {
                    required: true
                },
                typecard: {
                    required: true
                },
                numberCard: {
                    required: true
                },
                month: {
                    required: true
                },
                year: {
                    required: true
                },
                ccv: {
                    required: true
                }
            },
            messages: {
                nombres: "Ingrese su nombre",
                email: {
                    required: "Ingrese un email",
                    email: "Ingrese email valido"
                },
                countries: "Elige su país",
                ciudad: "Ingrese su ciudad",
                direccion: "Ingrese su dirección",
                typecard: "Seleccione una tarjeta",
                numberCard: "Ingrese Nº de tarjeta",
                month: "Mes",
                year: "Año",
                ccv: "Ingrese CVC"
            },
            submitHandler: function (form) {
                og.guardarFormulario('CC')
            }
        });
    });

</script>
