  <div class="row">
    <div class="col-md-12">
      <div class="data_pagos border_form text_align_form">
        <div class="bgGrisDark pTitleSub text-center mayus blanco"><span class="iLeft">1</span> <strong>Verificación de pago</strong></div>
        <div class="bgBlanco cnt_form">
          <h1>Gracias por su compra</h1>
          <p>Toda la información le llegara al correo en breves momentos</p>

          <p class="text-center"><a class="btn btn-lg bNaranja mayus text-center" id="btnBack" href="embajadores.biialab.org/dashboard.php">Regresar al dashboard</a></p>
        </div>

      </div>

    </div>
  </div>
<?php echo $this->headLink()->prependStylesheet($this->server()->getStatic() . 'css/jquery.alerts.css');?>
<?php echo $this->headScript()->prependFile($this->server()->getStatic() . 'js/jquery.alerts.js'); ?>
<script>

</script>
