<!-- BEGIN JAVASCRIPT -->
<?php
echo $this->headScript()
        ->prependFile($this->server('static', 'js/main.js', true))
        ->prependFile($this->server('static', 'assets/js/core/source/AppVendor.js', true))
        ->prependFile($this->server('static', 'assets/js/core/source/AppNavSearch.js', true))
        ->prependFile($this->server('static',  'assets/js/core/source/AppForm.js', true))
        ->prependFile($this->server('static',  'assets/js/core/source/AppCard.js', true))
        ->prependFile($this->server('static',  'assets/js/core/source/AppOffcanvas.js', true))
        ->prependFile($this->server('static',  'assets/js/core/source/AppNavigation.js', true))
        ->prependFile($this->server('static',  'assets/js/core/source/App.js', true))
        ->prependFile($this->server('static',  'assets/js/libs/rickshaw/rickshaw.min.js', true))
        ->prependFile($this->server('static',  'assets/js/libs/d3/d3.min.js', true))
        ->prependFile($this->server('static',  'assets/js/libs/nanoscroller/jquery.nanoscroller.min.js', true))
        ->prependFile($this->server('static',  'assets/js/libs/sparkline/jquery.sparkline.min.js', true))
        ->prependFile($this->server('static',  'assets/js/libs/jquery-knob/jquery.knob.min.js', true))
        ->prependFile($this->server('static',  'assets/js/libs/flot/jquery.flot.pie.js', true))
        ->prependFile($this->server('static',  'assets/js/libs/flot/jquery.flot.orderBars.js', true))
        ->prependFile($this->server('static',  'assets/js/libs/flot/jquery.flot.resize.min.js', true))
        ->prependFile($this->server('static',  'assets/js/libs/flot/jquery.flot.time.min.js', true))
        ->prependFile($this->server('static',  'assets/js/libs/flot/jquery.flot.min.js', true))
        ->prependFile($this->server('static',  'assets/js/libs/moment/moment.min.js', true))
        ->prependFile($this->server('static',  'assets/js/libs/autosize/jquery.autosize.min.js', true))
        ->prependFile($this->server('static',  'assets/js/libs/spin.js/spin.min.js', true))
        ->prependFile($this->server('static',  'assets/js/libs/bootstrap/bootstrap.min.js', true))
        ->prependFile($this->server('static',  'assets/js/libs/jquery/jquery-migrate-1.2.1.min.js', true));
?>
<!-- END JAVASCRIPT -->
