<!-- BEGIN CONTENT-->
<div id="content">
    <!-- BEGIN BLANK SECTION -->
    <section>
        <div class="section-header">
            <ol class="breadcrumb">
                <li><a href="/">inicio</a></li>
                <li class="">Seguridad</li>
                <li class="active">Lista de usuarios</li>
            </ol>
        </div><!--end .section-header -->
        <div class="section-body">
            <div class="row">
                <div class="col-md-12">
                    <div class="card card-bordered style-gray-bright">
                        <div class="card-body">
                            <label>Rol&nbsp;:&nbsp;</label>
                            <select name="">
                                <option value="">-Selecccionar-</option>
                            </select>
                            <a href="/admin/seguridad/usuario-form" class="btn ink-reaction btn-flat btn-default-dark">Nuevo</a>
                        </div>
                    </div>

                </div>
            </div>
            <div class="card">
                <div class="card-body">
                    <div class="row">
                        <div class="col-lg-12">
                            <div class="table-responsive">
                                <table id="datatable1" class="table table-striped table-hover">
                                    <thead>
                                        <tr>
                                            <th class="text-center" style="width: 20px;">Estado</th>
                                            <th>Usuario</th>
                                            <th>Nombre</th>
                                            <th>Apellido</th>
                                            <th>Rol</th>
                                            <th class="text-right">Acción</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <tr class="gradeX">
                                            <td class="text-center">
                                                <i class="md md-radio-button-on text-success"></i>
                                            </td>
                                            <td>joaquin</td>
                                            <td>Joaquin Mike</td>
                                            <td>Tarazona</td>
                                            <td>Administrador</td>
                                            <td class="text-right">
                                                <a href="/admin/seguridad/usuario-form">
                                                    <button data-original-title="Editar" data-placement="top" data-toggle="tooltip" 
                                                        class="btn btn-icon-toggle" type="button">
                                                        <i class="fa fa-pencil"></i>
                                                    </button>
                                                </a>
                                            </td>
                                        </tr>
                                        <tr class="gradeX">
                                            <td class="text-center">
                                                <i class="md md-radio-button-on text-default-light"></i>
                                            </td>
                                            <td>joaquin</td>
                                            <td>Joaquin Mike</td>
                                            <td>Tarazona</td>
                                            <td>Administrador</td>
                                            <td class="text-right">
                                                <a href="/admin/seguridad/usuario-form">
                                                    <button data-original-title="Editar" data-placement="top" data-toggle="tooltip" 
                                                        class="btn btn-icon-toggle" type="button">
                                                        <i class="fa fa-pencil"></i>
                                                    </button>
                                                </a>
                                            </td>
                                        </tr>
                                    </tbody>
                                </table>
                            </div><!--end .table-responsive -->
                        </div><!--end .col -->
                    </div><!--end .row -->
                </div>
            </div>


        </div><!--end .section-body -->
    </section>
    <!-- BEGIN BLANK SECTION -->
</div>