<!-- BEGIN CONTENT-->
<div id="content">
    <!-- BEGIN BLANK SECTION -->
    <section>
        <div class="section-header">
            <ol class="breadcrumb">
                <li><a href="/">Home</a></li>
                <li class="active">Lista de Usuarios</li>
            </ol>
        </div><!--end .section-header -->
        <div class="section-body">
            <div class="card">
                
                 <!-- BEGIN SEARCH HEADER -->
                <div class="card-head style-primary">
                    <div class="tools pull-right">
                        <form role="search" class="navbar-search">
                            <div class="form-group">
                                <input type="text" placeholder="Enter your keyword" name="contactSearch" class="form-control">
                            </div>
                            <button class="btn btn-icon-toggle ink-reaction" type="submit"><i class="fa fa-search"></i></button>
                        </form>
                    </div>
                </div><!--end .card-head -->
                <!-- END SEARCH HEADER -->
                
                <div class="card-body">
                    
                    <div class="row">

                        <!-- BEGIN SEARCH NAV -->
                        <div class="col-sm-4 col-md-3 col-lg-3">
                            <form id="form-filter" action="" method="get">
                                
                                <ul class="nav nav-pills nav-stacked">
                                    <li><small>Filtro</small></li>
                                    <li class="active">
                                        <div class="form-group">
                                            <label for="tipopers" class="control-label">Tipo Personal</label>
                                            <?php echo $this->formRow($this->formFilter->get('pers_tipo'))?>
                                        </div>
                                    </li>
                                    <li>
                                        <div class="form-group">
                                            <label for="Lastname5" class="control-label">Área laboral</label>
                                            <?php echo $this->formRow($this->formFilter->get('pers_area'))?>
                                        </div>
                                    </li>
                                    <li>
                                        <div class="form-group">
                                            <label for="Lastname5" class="control-label">Cargo</label>
                                            <?php echo $this->formRow($this->formFilter->get('pers_cargo'))?>
                                        </div>
                                    </li>
                                    <li>
                                        <div class="form-group">
                                            <label for="Lastname5" class="control-label">Género</label>
                                            <?php echo $this->formRow($this->formFilter->get('pers_sexo'))?>
                                        </div>
                                    </li>
                                    <li>
                                        <div class="form-group">
                                            <label for="Lastname5" class="control-label">Estado Civil</label>
                                            <?php echo $this->formRow($this->formFilter->get('pers_civil'))?>
                                        </div>
                                    </li>
                                    <li>
                                        <div class="form-group">
                                            <label for="Lastname5" class="control-label">Estado</label>
                                            <?php echo $this->formRow($this->formFilter->get('pers_estado'))?>
                                        </div>
                                    </li>
                                    <li>
                                        <div class="form-group">
                                            <button type="button" class="btn ink-reaction btn-flat btn-primary" onclick="getRestoreFilter('/application/usuario/lista')">
                                                Limpiar
                                            </button>
                                        </div>
                                    </li>
                                </ul>
                            </form>
                        </div><!--end .col -->
                        <!-- END SEARCH NAV -->
                        
                        
                        <div class="col-sm-8 col-md-9 col-lg-9">
                            

                            <div class="margin-bottom-xxl">
                                <span class="text-light text-lg">Página <strong>
                                    <?php echo $this->paginator->getCurrentPageNumber()?></strong> de 
                                    <strong><?php echo $this->paginator->count()?></strong>
                                    - <?php echo $this->paginator->getTotalItemCount()?> registros</span>
<!--                                <div class="btn-group btn-group-sm pull-right">
                                    <button data-toggle="dropdown" class="btn btn-default-light dropdown-toggle" type="button">
                                        <span class="glyphicon glyphicon-arrow-down"></span> Ordenar
                                    </button>
                                    <ul role="menu" class="dropdown-menu dropdown-menu-right animation-dock">
                                        <li><a href="#">Nombre</a></li>
                                        <li><a href="#">Apellido</a></li>
                                        <li><a href="#">Correo</a></li>
                                    </ul>
                                </div>-->
                            </div><!--end .margin-bottom-xxl -->
                            <div class="list-results">
                                <?php foreach ($this->paginator as $value) { ?>
                                    <div class="col-xs-12 col-lg-6 hbox-xs">
                                        <div class="hbox-column width-2">
                                            <?php if(!empty($value['codigo'])) { ?>
                                                <img alt="" src="<?php echo $this->server('imagen') . $value['codigo']?>.png" style="max-width: 72% !important"
                                                     class="img-circle img-responsive pull-left" 
                                                    onerror="this.src='<?php echo $this->server('static','assets/img/avatar9.jpg',true)?>'" />
                                            <?php }else { ?>
                                                 <img alt="" src="<?php echo $this->server('static','assets/img/avatar9.jpg',true)?>" 
                                                     class="img-circle img-responsive pull-left" />
                                            <?php } ?>
                                                
                                        </div><!--end .hbox-column -->
                                        <div class="hbox-column v-top">
                                            <div class="clearfix">
                                                <div class="col-lg-12 margin-bottom-lg">
                                                    <a href="" class="text-lg text-medium">
                                                        <?php echo $value['apepatper'] . ' ' . $value['apematper'] . ', ' . $value['nombreper']?>
                                                    </a>
                                                </div>
                                            </div>
                                            <div class="clearfix opacity-75">
                                                <div class="col-md-12">
                                                    <span class="glyphicon glyphicon-phone text-sm"></span> 
                                                    &nbsp;<?php echo $value['telefono']?>
                                                </div>
                                            </div>
                                            <div class="clearfix">
                                                <div class="col-md-12">
                                                    <span class="opacity-75">
                                                        <span class="glyphicon glyphicon-envelope text-sm"></span> 
                                                        &nbsp;<?php echo $value['email']?>
                                                    </span>
                                                    
                                                </div>
                                            </div>
                                        </div><!--end .hbox-column -->
                                    </div><!--end .hbox-xs -->
                                <?php } ?>
                            </div><!--end .list-results -->

                            <?php echo $this->paginationControl($this->paginator, 'sliding', 'application/paginador/sliding.phtml'); ?>

                        </div><!--end .col -->
                    </div><!--end .row -->
                </div><!--end .card-body -->

            </div>
        </div><!--end .section-body -->
    </section>
    <!-- BEGIN BLANK SECTION -->
</div>

<script type="text/javascript">
    function getFilterPersonal(){
        $('#form-filter').submit();
    }
   
</script>