<!-- BEGIN CONTENT-->
<div id="content">
    <!-- BEGIN BLANK SECTION -->
    <section>
        <div class="section-header">
            <ol class="breadcrumb">
                <li><a href="/">Home</a></li>
                <li class="active">Lista de Usuarios</li>
            </ol>
        </div><!--end .section-header -->
        <div class="section-body">
            <div class="card">

                <!-- BEGIN SEARCH HEADER -->
                <div class="card-head style-primary">
                    <div class="tools pull-left">
                        <form role="search" class="navbar-search">
                            <div class="form-group">
                                <input type="text" placeholder="Enter your keyword" name="contactSearch" class="form-control">
                            </div>
                            <button class="btn btn-icon-toggle ink-reaction" type="submit"><i class="fa fa-search"></i></button>
                        </form>
                    </div>
                </div><!--end .card-head -->
                <!-- END SEARCH HEADER -->

                <!-- BEGIN SEARCH RESULTS -->
                <div class="card-body">
                    <div class="row">

                        <!-- BEGIN SEARCH NAV -->
                        <div class="col-sm-4 col-md-3 col-lg-2">
                            <ul class="nav nav-pills nav-stacked">
                                <li><small>Categorías</small></li>
                                <li class="active">
                                    <a href="">
                                        General <small class="pull-right text-bold opacity-75">153</small>
                                    </a>
                                </li>
                                <li>
                                    <a href="">
                                        Categoría1 <small class="pull-right text-bold opacity-75">16</small>
                                    </a>
                                </li>
                                <li>
                                    <a href="">
                                        Categoría2 <small class="pull-right text-bold opacity-75">76
                                        </small>
                                    </a>
                                </li>
                            </ul>
                        </div><!--end .col -->
                        <!-- END SEARCH NAV -->

                        <div class="col-sm-8 col-md-9 col-lg-10">

                            <!-- BEGIN SEARCH RESULTS LIST -->
                            <div class="margin-bottom-xxl">
                                <span class="text-light text-lg">Página <strong><?php echo $this->paginator->getCurrentPageNumber()?></strong> de <strong><?php echo $this->paginator->count()?></strong></span>
                                <div class="btn-group btn-group-sm pull-right">
                                    <button data-toggle="dropdown" class="btn btn-default-light dropdown-toggle" type="button">
                                        <span class="glyphicon glyphicon-arrow-down"></span> Ordenar
                                    </button>
                                    <ul role="menu" class="dropdown-menu dropdown-menu-right animation-dock">
                                        <li><a href="#">Nombre</a></li>
                                        <li><a href="#">Apellido</a></li>
                                        <li><a href="#">Correo</a></li>
                                    </ul>
                                </div>
                            </div><!--end .margin-bottom-xxl -->
                            <div class="list-results">
                                <?php foreach ($this->paginator as $value) { ?>
                                    <div class="col-xs-12 col-lg-6 hbox-xs">
                                        <div class="hbox-column width-2">
                                            <img alt="" src="../../../assets/img/avatar9.jpg?1404026744" class="img-circle img-responsive pull-left">
                                        </div><!--end .hbox-column -->
                                        <div class="hbox-column v-top">
                                            <div class="clearfix">
                                                <div class="col-lg-12 margin-bottom-lg">
                                                    <a href="" class="text-lg text-medium">
                                                        <?php echo $value['apepatper'] . ' ' . $value['apematper'] . ', ' . $value['nombreper']?>
                                                    </a>
                                                </div>
                                            </div>
                                            <div class="clearfix opacity-75">
                                                <div class="col-md-12">
                                                    <span class="glyphicon glyphicon-phone text-sm"></span> 
                                                    &nbsp;<?php echo $value['telefono']?>
                                                </div>
                                            </div>
                                            <div class="clearfix">
                                                <div class="col-md-12">
                                                    <span class="opacity-75">
                                                        <span class="glyphicon glyphicon-envelope text-sm"></span> 
                                                        &nbsp;<?php echo $value['email']?>
                                                    </span>
                                                    
                                                </div>
                                            </div>
                                        </div><!--end .hbox-column -->
                                    </div><!--end .hbox-xs -->
                                <?php } ?>
                            </div><!--end .list-results -->

                            <?php echo $this->paginationControl($this->paginator, 'sliding', 'application/paginador/sliding.phtml'); ?>

                            <!-- BEGIN SEARCH RESULTS PAGING -->
<!--                            <div class="text-center">
                                <ul class="pagination">
                                    <li class="disabled"><a href="#">«</a></li>
                                    <li class="active"><a href="#">1 <span class="sr-only">(current)</span></a></li>
                                    <li><a href="#">2</a></li>
                                    <li><a href="#">3</a></li>
                                    <li><a href="#">4</a></li>
                                    <li><a href="#">5</a></li>
                                    <li><a href="#">»</a></li>
                                </ul>
                            </div>end .text-center -->

                            <!-- BEGIN SEARCH RESULTS PAGING -->
                        </div><!--end .col -->
                    </div><!--end .row -->
                </div><!--end .card-body -->
                <!-- END SEARCH RESULTS -->

            </div>
        </div><!--end .section-body -->
    </section>

    <!-- BEGIN BLANK SECTION -->
</div>