<script src="<?php echo $this->server('static', 'assets/js/libs/raphael/raphael-min.js', true)?>"></script>
<script src="<?php echo $this->server('static', 'assets/js/libs/morris.js/morris.min.js', true)?>"></script>
<!-- BEGIN CONTENT-->
<div id="content">
    <section>
        <div class="section-header">
            <ol class="breadcrumb">
                 <?php echo \Application\Entity\Functions::getBreadCrumb($this->site, 'Usuario')?>
            </ol>
        </div><!--end .section-header -->
        <div class="section-body contain-lg">

            <div class="row">
               <div class="col-lg-12">
                    <h2 class="text-primary">Diagrama charts</h2>
                </div>
                <div class="col-lg-12">
                    <h4>Examples</h4>
                </div>
                <div class="col-lg-3 col-md-4">
                    <article class="margin-bottom-xxl">
                        <p>
                            Lorem ipsum ad his scripta blandit partiendo, eum fastidii accumsan euripidis in, eum liber hendrerit an. 
                            Qui ut wisi vocibus suscipiantur, quo dicit ridens inciderint id. Quo mundi lobortis reformidans eu, 
                            legimus senserit definiebas an eos.
                        </p>
                    </article>
                </div><!--end .col -->
                <div class="col-lg-offset-1 col-md-8">
                    <div class="card">
                        <div class="card-body">
                            <div id="morris-bar-graph" class="height-7" data-colors="#2196F3,#0aa89e"></div>
                        </div><!--end .card-body -->
                    </div><!--end .card -->
                    <em class="text-caption">Grouped bar chart</em>
                </div><!--end .col -->
            </div><!--end .row -->


        </div><!--end .section-body -->
    </section>


</div><!--end #content-->
<!-- END CONTENT -->
<script type="text/javascript">
    Morris.Bar({
        element: 'morris-bar-graph',
        data: [
            {x: '2011 Q1', y: 3, z: 2},
            {x: '2011 Q2', y: 2, z: null},
            {x: '2011 Q3', y: 0, z: 2},
            {x: '2011 Q4', y: 2, z: 4}
        ],
        xkey: 'x',
        ykeys: ['y', 'z'],
        labels: ['Y', 'Z'],
        barColors: $('#morris-bar-graph').data('colors').split(',')
    });

</script>