<?php if($this->tipo == \Application\Entity\Functions::GRAFICO_BARRAS) { ?>
    <div id="container" style="min-width: 310px; height: 400px; margin: 0 auto"></div>
<?php }elseif($this->tipo == \Application\Entity\Functions::GRAFICO_CIRCULAR) { ?>
    <div id="container" style="min-width: 310px; height: 400px; margin: 0 auto"></div>
<?php } ?>

<script type="text/javascript">
    <?php if($this->tipo == \Application\Entity\Functions::GRAFICO_BARRAS) { ?>
        $(function () {
            // Create the chart
            $('#container').highcharts({
                chart: {
                    type: 'column'
                },
                title: {
                    text: '<?php echo $this->abogado?>'
                },
                subtitle: {
                    text: '<?php echo $this->nombre?>'
                },
                xAxis: {
                    type: 'category'
                },
                yAxis: {
                    title: {
                        text: 'Total porcentaje en Tiempo'
                    }

                },
                legend: {
                    enabled: false
                },
                plotOptions: {
                    series: {
                        borderWidth: 0,
                        dataLabels: {
                            enabled: true,
                            format: '{point.y}'
                        }
                    }
                },

                tooltip: {
                    headerFormat: '',//'<span style="font-size:11px">{series.name} </span><br>',
                    pointFormat: '<span style="color:{point.color}">{point.name}</span>: <b>{point.y} Horas</b> <br/>'
                },

                series: [{
                    name: "Cliente",
                    colorByPoint: true,
                    data: [            
                    <?php foreach ($this->data as $value) { ?>
                        {name: "<?php echo $value['cliente'];?>", y: <?php echo $value['tiempo'];?>,drilldown: "<?php echo $value['cliente'];?>"},                         
                    <?php } ?>
                    ]
                }],
                drilldown: {
                    series: [
                    <?php foreach ($this->data as $value) { ?>
                    {name: "<?php echo $value['cliente'];?>",id: "<?php echo $value['cliente'];?>",
                        data: [
                            ["v11.0",24.13],
                            ["v8.0",17.2],
                            ["v9.0",8.11],
                            ["v10.0",5.33],
                            ["v6.0",1.06],
                            ["v7.0",0.5]
                        ]
                    },  
                    <?php } ?>
                    ]
                }
            });
        });
    <?php }elseif($this->tipo == \Application\Entity\Functions::GRAFICO_CIRCULAR) { ?>
        $(function () {
            $('#container').highcharts({
                chart: {
                    plotBackgroundColor: null,
                    plotBorderWidth: null,
                    plotShadow: false,
                    type: 'pie'
                },
                title: {
                    text: '<?php echo $this->abogado?>'
                },
                subtitle: {
                    text: '<?php echo $this->nombre?>'
                }, 
                tooltip: {
                    //pointFormat: '{series.name}: <b>{point.y} Horas</b>'
                    pointFormat: '<b>{point.y} Horas ({point.percentage:.1f}%)</b>'
                },
                plotOptions: {
                    pie: {
                        allowPointSelect: true,
                        cursor: 'pointer',
                        dataLabels: {
                            enabled: true,
                            format: '<b>{point.name} </b> {point.y}',
                            style: {
                                color: (Highcharts.theme && Highcharts.theme.contrastTextColor) || 'black'
                            }
                        },
                        showInLegend: true
                    }
                },
                series: [{
                    name: "Tiempo",
                    colorByPoint: true,
                    data: [                
                            <?php foreach ($this->data as $value) { ?>
                                {name: "<?php echo $value['cliente'];?>", y: <?php echo $value['tiempo'];?>},                         
                            <?php } ?>
                          ]
                }]
            });                                
        });
    <?php } ?>
</script>