<!-- BEGIN CONTENT-->
<link type="text/css" rel="stylesheet" href="<?php echo $this->server('static', 'assets/css/theme-default/libs/bootstrap-datepicker/datepicker3', true)?>" />
<div id="content">
    <section>
        <div class="section-header">
            <ol class="breadcrumb">
                 <?php echo \Application\Entity\Functions::getBreadCrumb($this->site, 'Grafico')?>
            </ol>
        </div><!--end .section-header -->
        <div class="section-body contain-lg">
            <div class="row">
                <div class="col-lg-12">
                    <div class="col-lg-8">
                        <h2 class="text-primary">Área charts</h2>
                        <h4>Horas x Cliente - <?php echo $this->nombre?></h4>
                    </div>
                    <div class="col-lg-4">
                        <div class="btn-group btn-group-sm pull-right">
                            <button type="button" class="btn btn-default-light dropdown-toggle" data-toggle="dropdown">
                                    <span class="glyphicon glyphicon-arrow-down"></span> Tipo
                            </button>
                            <ul class="dropdown-menu dropdown-menu-right animation-dock" role="menu">
                                <li class="<?php echo ($tipo == \Application\Entity\Functions::GRAFICO_CIRCULAR) ? 'active' : ''?>">
                                    <a href="/application/reporte/personal?<?php echo \Auth\Entity\AuthPersonal::getUrlReportePersonal($this->codigo,\Application\Entity\Functions::GRAFICO_CIRCULAR)?>&site=<?php echo \Application\Entity\Functions::SITE_PERSONAL?>">
                                        Circular
                                    </a>
                                </li>
                                 <li class="<?php echo ($tipo == \Application\Entity\Functions::GRAFICO_BARRAS) ? 'active' : ''?>">
                                    <a href="/application/reporte/personal?<?php echo \Auth\Entity\AuthPersonal::getUrlReportePersonal($this->codigo,\Application\Entity\Functions::GRAFICO_BARRAS)?>&site=<?php echo \Application\Entity\Functions::SITE_PERSONAL?>">
                                        Barras
                                    </a>
                                </li>
                            </ul>
                        </div>
                   </div>
                </div>
                <div class="col-lg-12">
                    <div class="row">
                        <hr class="ruler-xxl" style="margin: 10px 0 15px 0">
                    </div>
                </div>
                
                <div class="col-lg-12">
                    <div class="row">
                        <div class="col-lg-4 col-md-3">
                            <form id="form-filter" action="" method="post" class="form">
                                <input type="hidden" name="form_tipo" id="form_tipo" value="<?php echo $this->tipo?>">
                                <div class="form-group">
                                    <label>Año desde - Año hasta</label>
                                    <div class="input-daterange input-group" id="demo-date-range">
                                        <div class="input-group-content">
                                            <?php echo $this->formRow($this->formFilter->get('anio_start'))?>
                                        </div>
                                        <span class="input-group-addon">-</span>
                                            <div class="input-group-content">
                                               <?php echo $this->formRow($this->formFilter->get('anio_end'))?>
                                            </div>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label>Mes desde - Mes hasta</label>
                                    <div class="input-daterange input-group" id="demo-date-range">
                                        <div class="input-group-content">
                                            <?php echo $this->formRow($this->formFilter->get('mes_start'))?>
                                        </div>
                                        <span class="input-group-addon">-</span>
                                            <div class="input-group-content">
                                               <?php echo $this->formRow($this->formFilter->get('mes_end'))?>
                                            </div>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <div class="input-daterange input-group" id="demo-date-range">
                                        <div class="input-group-content">
                                            <?php echo $this->formRow($this->formFilter->get('date_start'))?>
                                            <label>Fecha rango</label>
                                        </div>
                                        <span class="input-group-addon">a</span>
                                            <div class="input-group-content">
                                                <?php echo $this->formRow($this->formFilter->get('date_end'))?>
                                                <div class="form-control-line"></div>
                                            </div>
                                    </div>
                                </div>
                                <div class="row">
                                    <hr class="ruler-xxl" style="margin: 10px 0 15px 0">
                                </div>
                                <div class="form-group">
                                     <label>Área</label>
                                     <?php echo $this->formRow($this->formFilter->get('pers_area'))?>
                                </div>
                                <div class="form-group">
                                    <label>Personal</label>
                                    <div style="height: 350px; overflow-y: scroll;">
                                        <table class="table table-striped">
                                            <thead>
                                                <tr>
                                                    <th>#</th>
                                                    <th>Nombre</th>
                                                </tr>
                                            </thead>
                                            <tbody id="table-personal">
                                                <?php foreach ($this->lista as $personal) { ?>
                                                    <?php $check = ''?>
                                                    <?php if($personal['pers_id'] == $this->personal['pers_id']) { ?>
                                                         <?php $check = 'checked="checked"'?>
                                                    <?php } ?>
                                                    <tr>
                                                        <td>
                                                            <input type="checkbox" name="personal[<?php echo $personal['pers_id']?>]" 
                                                                id="personal[<?php echo $personal['pers_id']?>]" value="<?php echo $personal['pers_id']?>" <?php echo $check?>/>
                                                        </td>
                                                        <td>
                                                            <?php echo $personal['apepatper']. ' ' . $personal['apematper'] . ', ' .
                                                                $personal['nombreper']
                                                            ?>
                                                        </td>
                                                    </tr>

                                                <?php }?>
                                            </tbody>
                                        </table>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <button class="btn ink-reaction btn-raised btn-sm btn-primary" type="button" onclick="getGenerarGrafico()">
                                        Generar
                                    </button>
                                </div>
                            </form>
                            
                        </div>
                        <div class="col-md-8">
                            <div class="card">
                                <div id="personal-graph" class="card-body">
                                    
                                </div><!--end .card-body -->
                            </div><!--end .card -->
                            <em class="text-caption">Grouped bar chart</em>
                        </div><!--end .col -->
                    </div>
                </div>
               
            </div><!--end .row -->


        </div><!--end .section-body -->
    </section>
</div><!--end #content-->
<!-- END CONTENT -->
<script src="<?php echo $this->server('static', 'assets/js/libs/raphael/raphael-min.js', true)?>"></script>
<script src="<?php echo $this->server('static', 'assets/js/libs/morris.js/morris.min.js', true)?>"></script>
<script src="<?php echo $this->server('static', 'assets/js/libs/bootstrap-datepicker/bootstrap-datepicker.js', true)?>"></script>
<script src="<?php echo $this->server('static', 'assets/js/libs/bootstrap-datepicker/locales/bootstrap-datepicker.es', true)?>"></script>
<script type="text/javascript">
    $(document).ready(function() {
        $('#date_start').datepicker({format: 'dd/mm/yyyy',language: 'es',
            autoclose: true,
            onSelect: function(selected) {
               $("#date_end").datepicker("option","minDate", selected)
            }
        }).on('changeDate',function(ev){
            //alert($("#date_end").val());
            getGenerarGrafico();
        });
       
        $('#date_end').datepicker({format: 'dd/mm/yyyy',language: 'es',
            autoclose: true,
            onSelect: function(selected) {
                alert(selected);
             }
       
        }).on('changeDate',function(ev){
            //alert($("#date_end").val());
            getGenerarGrafico();
        });
    });
    
    function getListaPersonal(id){
        $.ajax({
            url: '/application/reporte/personal-lista',
            data: {'id': id.value},
            type: 'POST',
            beforeSend: function() {
               $('#table-personal').html('<tr><td>Cargando...</td></tr>')
            },
            success: function(json) {
                var result = '';
                if(json.success == 1){
                    $.each(json.data, function(i, item) {
                        result += '<tr><td>';
                        result += '<input type="checkbox" name="personal[' + item.pers_id + ']" id="personal[' + item.pers_id + ']" value="' + item.pers_id + '" />';
                        result += '</td><td>';
                        result += item.apepatper + ' ' + item.apematper + ', ' + item.nombreper;
                        result += '</td></tr>';
                    });
                    $('#table-personal').html(result);
                    getGenerarGrafico();
                }
            },
            dataType: 'json'
        });
        return false;
    }
    
    function getGenerarGrafico(){
        var form = $('#form-filter').serialize();
        $.ajax({
            url: '/application/reporte/personal-grafico',
            data: form,
            type: 'POST',
            beforeSend: function() {
               $('#personal-graph').html('<img src="<?php echo $this->server('static', 'img/cargando.gif', true)?>" title="Cargando Grafico">')
            },
            success: function(html) {
                $('#personal-graph').html(html)
            },
            dataType: 'html'
        });
        return false;
    }
    
    window.onload = function() {
        getGenerarGrafico();
    }
</script>

<style>
    .form-control {
        font-size: 12px !important;
        height: 25px !important;
        padding: 0;
    }
    body{
        line-height: 1!important;
    }
</style>