<!-- BEGIN CONTENT-->
<div id="content">
    <section>
        <div class="section-header">
            <ol class="breadcrumb">
                 <?php echo \Application\Entity\Functions::getBreadCrumb($this->site, 'Grafico')?>
            </ol>
        </div><!--end .section-header -->
        <div class="section-body contain-lg">

            <div class="row">
               <div class="col-lg-12">
                    <h2 class="text-primary">Área charts</h2>
                    <h4>Horas x Cliente</h4>
                </div>
                <div class="col-lg-12">
                    <div class="card">
                        <div class="card-body">
                            <?php if($this->tipo == \Application\Entity\Functions::GRAFICO_BARRAS) { ?>
                                <div id="morris-graph" class="height-7" data-colors="#2196F3,#0aa89e"></div>
                            <?php }elseif($this->tipo == \Application\Entity\Functions::GRAFICO_CIRCULAR) { ?>
                                <div id="morris-graph" class="height-6" data-colors="#9C27B0,#2196F3,#0aa89e,#FF9800"></div>
                            <?php } ?>
                        </div><!--end .card-body -->
                    </div><!--end .card -->
                    <em class="text-caption">Grouped bar chart</em>
                </div><!--end .col -->
            </div><!--end .row -->


        </div><!--end .section-body -->
    </section>


</div><!--end #content-->
<!-- END CONTENT -->
<script src="<?php echo $this->server('static', 'assets/js/libs/raphael/raphael-min.js', true)?>"></script>
<script src="<?php echo $this->server('static', 'assets/js/libs/morris.js/morris.min.js', true)?>"></script>
<?php if($this->tipo == \Application\Entity\Functions::GRAFICO_BARRAS) { ?>
    <script type="text/javascript">
        Morris.Bar({
            element: 'morris-graph',
            data: [
                {x: '2011 Q1', y: 10},
                {x: '2011 Q2', y: 2},
                {x: '2011 Q3', y: 0},
                {x: '2011 Q4', y: 2}
            ],
            xkey: 'x',
            ykeys: ['y'],
            labels: ['Y'],
            barColors: $('#morris-graph').data('colors').split(',')
        });

    </script>
<?php }elseif($this->tipo == \Application\Entity\Functions::GRAFICO_CIRCULAR) { ?>
    <script type="text/javascript">
        Morris.Donut({
            element: 'morris-graph',
            data: [
                {value: 70, label: 'foo', formatted: 'at least 70%'},
                {value: 15, label: 'bar', formatted: 'approx. 15%'},
                {value: 10, label: 'baz', formatted: 'approx. 10%'},
                {value: 5, label: 'A really really long label', formatted: 'at most 5%'}
            ],
            colors: $('#morris-graph').data('colors').split(','),
            formatter: function (x, data) {
                return data.formatted;
            }
        });
    </script>
<?php } ?>
