<!-- BEGIN CONTENT-->
<div id="content">
    <!-- BEGIN BLANK SECTION -->
    <section>
        <div class="section-header">
            <ol class="breadcrumb">
                <li><a href="/">inicio</a></li>
                <li class="active">Panel</li>
            </ol>
        </div><!--end .section-header -->
        <div class="section-body">
            <div class="row">
                <div class="col-md-9">
                    <div class="card">
                        <div class="card-body no-padding">
                            <ul class="list divider-full-bleed">
                                <li class="tile" style="padding-left: 16px;">
                                    <div class=" tile-text">
                                        <?php echo 'Nombre : ' . $this->layout()->dataUser['us_nombre']?>
                                    </div>
                                </li>
                                <li class="tile" style="padding-left: 16px;">
                                    <div class="tile-text">
                                        <?php echo 'Rol : ' . $this->layout()->dataUser['rol_desc'] ?>
                                    </div>
                                </li>
                                <li class="tile" style="padding-left: 16px;">
                                    <div class="tile-text">
                                        <?php echo 'Personal Código : ' . $this->layout()->dataUser['pers_code'] ?>
                                    </div>
                                </li>
                            </ul>
                        </div><!--end .card-body -->
                    </div>
                </div>
            </div>
        </div><!--end .section-body -->
    </section>
    <!-- BEGIN BLANK SECTION -->
</div>