<!-- BEGIN CONTENT-->
<div id="content">
    <section>
        <div class="section-body">
            <div class="row">
                <p>
                    <?php echo 'Usuario : ' . $this->userId?>
                </p>
                <p>
                    <?php echo 'Email   : ' . $this->userEmail?>
                </p>
            </div>
            <div class="row">
                <?php 
                    echo '<pre>';
                           print_r($_SESSION);
                           echo '</pre>';
                   ?>
            </div>
        </div>
    </section>
</div>