
CREATE TABLE sessions (
    id char(32) NOT NULL DEFAULT '',
    name varchar(255) NOT NULL,
    modified int(11) DEFAULT NULL,
    lifetime int(11) DEFAULT NULL,
    data text,
    PRIMARY KEY (id)
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8;
  
CREATE TABLE `auth_rol` (
  `rol_id` INT NOT NULL AUTO_INCREMENT,
  `rol_desc` VARCHAR(64) NULL,
  `rol_estado` INT(11) NULL DEFAULT 1,
  PRIMARY KEY (`rol_id`))
ENGINE = InnoDB;


CREATE TABLE `auth_personal` (
  `pers_id` INT NOT NULL AUTO_INCREMENT,
  `empcod` varchar(3) NOT NULL,
  `percod` varchar(11) NOT NULL,
  `codigo` varchar(11) DEFAULT NULL,
  `tipdoc` varchar(4) DEFAULT NULL,
  `nrodoc` varchar(20) DEFAULT NULL,
  `dni` varchar(10) DEFAULT NULL,
  `ruc` varchar(11) DEFAULT NULL,
  `nomcomper` varchar(100) DEFAULT NULL,
  `apepatper` varchar(100) DEFAULT NULL,
  `apematper` varchar(100) DEFAULT NULL,
  `nombreper` varchar(100) DEFAULT NULL,
  `nombreper2` varchar(100) DEFAULT NULL,
  `ubgcod` varchar(6) DEFAULT NULL,
  `direccion` varchar(120) DEFAULT NULL,
  `direccion2` varchar(120) DEFAULT NULL,
  `direccion3` varchar(120) DEFAULT NULL,
  `contacto` varchar(100) DEFAULT NULL,
  `calnumero` varchar(20) DEFAULT NULL,
  `relacion` varchar(3) DEFAULT NULL,
  `celularc` varchar(30) DEFAULT NULL,
  `tipoper` varchar(3) DEFAULT NULL,
  `area` varchar(4) DEFAULT NULL,
  `cargo` varchar(4) DEFAULT NULL,
  `telefono` varchar(30) DEFAULT NULL,
  `telefono2` varchar(30) DEFAULT NULL,
  `telefono3` varchar(30) DEFAULT NULL,
  `telefonodirec` varchar(30) DEFAULT NULL,
  `celular1` varchar(30) DEFAULT NULL,
  `celular2` varchar(30) DEFAULT NULL,
  `celular3` varchar(30) DEFAULT NULL,
  `email` varchar(100) DEFAULT NULL,
  `email2` varchar(100) DEFAULT NULL,
  `email3` varchar(100) DEFAULT NULL,
  `estado` varchar(1) DEFAULT NULL,
  `fching` datetime DEFAULT NULL,
  `fecnac` datetime DEFAULT NULL,
  `turbo` varchar(11) DEFAULT NULL,
  `anexo` varchar(5) DEFAULT NULL,
  `secretaria` varchar(11) DEFAULT NULL,
  `anexosec` varchar(5) DEFAULT NULL,
  `estcivil` varchar(3) DEFAULT NULL,
  `nrodepen` varchar(3) DEFAULT NULL,
  `coleprim` varchar(3) DEFAULT NULL,
  `colesecu` varchar(3) DEFAULT NULL,
  `instuniv` varchar(3) DEFAULT NULL,
  `titulo` varchar(3) DEFAULT NULL,
  `feccolegia` datetime DEFAULT NULL,
  `alergia` varchar(70) DEFAULT NULL,
  `seguro` varchar(1) DEFAULT NULL,
  `segurodes` varchar(3) DEFAULT NULL,
  `medicocab` varchar(70) DEFAULT NULL,
  `tipsangre` varchar(10) DEFAULT NULL,
  `quinta` varchar(1) DEFAULT NULL,
  `quintaact` varchar(1) DEFAULT NULL,
  `empleador` varchar(70) DEFAULT NULL,
  `afp` varchar(1) DEFAULT NULL,
  `afpdes` varchar(3) DEFAULT NULL,
  `fecafilia` datetime DEFAULT NULL,
  `sexo` varchar(1) DEFAULT NULL,
  `fecreg` datetime DEFAULT NULL,
  `usureg` varchar(20) DEFAULT NULL,
  `usumod` varchar(20) DEFAULT NULL,
  `loccod` varchar(3) DEFAULT NULL,
  `piso` varchar(3) DEFAULT NULL,
  `hostname` varchar(20) DEFAULT NULL,
  `ippc` varchar(20) DEFAULT NULL,
  `tipopc` varchar(3) DEFAULT NULL,
  `estpc` varchar(3) DEFAULT NULL,
  `userpc` varchar(20) DEFAULT NULL,
  `passuser` varchar(20) DEFAULT NULL,
  `folder` varchar(70) DEFAULT NULL,
  `passfono` varchar(20) DEFAULT NULL,
  `passscaner` varchar(20) DEFAULT NULL,
  `scanernom` varchar(50) DEFAULT NULL,
  `tratamiento` varchar(4) DEFAULT NULL,
  `pais` varchar(4) DEFAULT NULL,
  `codpais` varchar(10) DEFAULT NULL,
  `numfax` varchar(30) DEFAULT NULL,
  `idioma` varchar(4) DEFAULT NULL,
  `tarj_navidad` varchar(2) DEFAULT NULL,
  `inf_legal_varios_esp` varchar(2) DEFAULT NULL,
  `inf_legal_varios_ing` varchar(2) DEFAULT NULL,
  `inf_legal_minero_esp` varchar(2) DEFAULT NULL,
  `inf_legal_minero_ing` varchar(2) DEFAULT NULL,
  `eco_legal_esp` varchar(2) DEFAULT NULL,
  `eco_legal_ing` varchar(2) DEFAULT NULL,
  `anuncios` varchar(2) DEFAULT NULL,
  `observaciones` text,
  `secretariades` varchar(100) DEFAULT NULL,
  `feccese` datetime DEFAULT NULL,
  `motcese` varchar(100) DEFAULT NULL,
  `ubicades` varchar(100) DEFAULT NULL,
  `entfoto` varchar(1) DEFAULT NULL,
  `acargode` varchar(11) DEFAULT NULL,
  `modulo` varchar(4) DEFAULT NULL,
  `correopst` varchar(1) DEFAULT NULL,
  `accfolder` varchar(1) DEFAULT NULL,
  `urlmaili` varchar(100) DEFAULT NULL,
  `urlmaile` varchar(100) DEFAULT NULL,
  `firout` varchar(1) DEFAULT NULL,
  `firowa` varchar(1) DEFAULT NULL,
  `grupcorreo` varchar(100) DEFAULT NULL,
  `fecinduc` datetime DEFAULT NULL,
  `lugar` varchar(70) DEFAULT NULL,
  `participantes` varchar(50) DEFAULT NULL,
  `catcod` varchar(4) DEFAULT NULL,
  `gruanexo` varchar(4) DEFAULT NULL,
  `empresa` varchar(4) DEFAULT NULL,
  `especialidad` varchar(4) DEFAULT NULL,
  `archivo` varchar(100) DEFAULT NULL,
  `confoto` varchar(1) DEFAULT NULL,
  `reu` varchar(1) DEFAULT NULL,
  `reugru` varchar(1) DEFAULT NULL,
  `orden` int(11) DEFAULT NULL,
  `nouser` varchar(1) DEFAULT NULL,
  `fecreing` datetime DEFAULT NULL,
  `i_timeslip` varchar(1) DEFAULT NULL,
  `i_worldox` varchar(1) DEFAULT NULL,
  `i_etiqueta` varchar(1) DEFAULT NULL,
  `i_spijdesk` varchar(1) DEFAULT NULL,
  `i_spijweb` varchar(1) DEFAULT NULL,
  `i_turbo` varchar(1) DEFAULT NULL,
  `i_datalegal` varchar(1) DEFAULT NULL,
  `i_asistencia` varchar(1) DEFAULT NULL,
  `i_sispro` varchar(1) DEFAULT NULL,
  `i_fichaper` varchar(1) DEFAULT NULL,
  `i_ss2000` varchar(1) DEFAULT NULL,
  `i_siscont` varchar(1) DEFAULT NULL,
  `i_caja` varchar(1) DEFAULT NULL,
  `i_cid` varchar(1) DEFAULT NULL,
  `i_g` varchar(1) DEFAULT NULL,
  `i_j` varchar(1) DEFAULT NULL,
  `i_o` varchar(1) DEFAULT NULL,
  `i_m` varchar(1) DEFAULT NULL,
  `i_i` varchar(1) DEFAULT NULL,
  `i_h` varchar(1) DEFAULT NULL,
  `i_impresora` varchar(50) DEFAULT NULL,
  `i_templates` varchar(1) DEFAULT NULL,
  `i_pcsystel` varchar(1) DEFAULT NULL,
  `i_remoto` varchar(1) DEFAULT NULL,
  `i_antivirus` varchar(1) DEFAULT NULL,
  `i_firewall` varchar(1) DEFAULT NULL,
  `i_seguridad` varchar(1) DEFAULT NULL,
  `i_update` varchar(1) DEFAULT NULL,
  `i_ususunarp` varchar(20) DEFAULT NULL,
  `i_passunarp` varchar(20) DEFAULT NULL,
  `i_pasworldox` varchar(20) DEFAULT NULL,
  `i_usulegal` varchar(20) DEFAULT NULL,
  `i_paslegal` varchar(20) DEFAULT NULL,
  `i_ususpij` varchar(20) DEFAULT NULL,
  `i_urlint` varchar(1) DEFAULT NULL,
  `i_urlext` varchar(1) DEFAULT NULL,
  `trabajacon` varchar(50) DEFAULT NULL,
  `entfirma` varchar(1) DEFAULT NULL,
  `i_firmaow` varchar(30) DEFAULT NULL,
  `perfilweb` text,
  `w_nombres_s` text,
  `w_nombres_i` text,
  `w_educacion_s` text,
  `w_educacion_i` text,
  `w_colegiaturas_s` text,
  `w_colegiaturas_i` text,
  `w_membresia_1s` varchar(70) DEFAULT NULL,
  `w_membresia_2s` varchar(70) DEFAULT NULL,
  `w_membresia_3s` varchar(70) DEFAULT NULL,
  `w_membresia_1i` varchar(70) DEFAULT NULL,
  `w_membresia_2i` varchar(70) DEFAULT NULL,
  `w_membresia_3i` varchar(70) DEFAULT NULL,
  `w_idiomas_s` text,
  `w_idiomas_i` text,
  `w_expprof_s` text,
  `w_expprof_i` text,
  `w_expdoce_s` text,
  `w_expdoce_i` text,
  `w_transac_s` text,
  `w_transac_i` text,
  `w_administrativo` varchar(1) DEFAULT NULL,
  `w_aeronautico` varchar(1) DEFAULT NULL,
  `w_ambiental` varchar(1) DEFAULT NULL,
  `w_competencia` varchar(1) DEFAULT NULL,
  `w_corporativo` varchar(1) DEFAULT NULL,
  `w_electricidad` varchar(1) DEFAULT NULL,
  `w_financiero` varchar(1) DEFAULT NULL,
  `w_mercado` varchar(1) DEFAULT NULL,
  `w_fusiones` varchar(1) DEFAULT NULL,
  `w_infraestructura` varchar(1) DEFAULT NULL,
  `w_inmobilario` varchar(1) DEFAULT NULL,
  `w_laboral` varchar(1) DEFAULT NULL,
  `w_mineria` varchar(1) DEFAULT NULL,
  `w_petroleo` varchar(1) DEFAULT NULL,
  `w_propiedad` varchar(1) DEFAULT NULL,
  `w_proteccion` varchar(1) DEFAULT NULL,
  `w_solucion` varchar(1) DEFAULT NULL,
  `w_tributario` varchar(1) DEFAULT NULL,
  `w_otros` varchar(1) DEFAULT NULL,
  `w_otrosdes` text,
  `w_exprof_1s` varchar(70) DEFAULT NULL,
  `w_exprof_2s` varchar(70) DEFAULT NULL,
  `w_exprof_3s` varchar(70) DEFAULT NULL,
  `w_exprof_1i` varchar(70) DEFAULT NULL,
  `w_exprof_2i` varchar(70) DEFAULT NULL,
  `w_exprof_3i` varchar(70) DEFAULT NULL,
  `w_educaciond_s` varchar(70) DEFAULT NULL,
  `w_educaciond_i` varchar(70) DEFAULT NULL,
  `w_colegiaturad_s` varchar(70) DEFAULT NULL,
  `w_colegiaturad_i` varchar(70) DEFAULT NULL,
  `w_colegiatura_1s` varchar(70) DEFAULT NULL,
  `w_colegiatura_2s` varchar(70) DEFAULT NULL,
  `w_colegiatura_3s` varchar(70) DEFAULT NULL,
  `w_colegiatura_1i` varchar(70) DEFAULT NULL,
  `w_colegiatura_2i` varchar(70) DEFAULT NULL,
  `w_colegiatura_3i` varchar(70) DEFAULT NULL,
  `lugnac` varchar(100) DEFAULT NULL,
  PRIMARY KEY (`pers_id`),
  UNIQUE INDEX `percod_UNIQUE` (`percod` ASC)
)ENGINE = InnoDB;

CREATE TABLE `auth_usuario` (
  `us_id` INT NOT NULL AUTO_INCREMENT,
  `us_usuario` VARCHAR(32) NOT NULL,
  `us_password` VARCHAR(256) NOT NULL,
  `us_nombre` VARCHAR(256) NULL,
  `us_apellidos` VARCHAR(45) NULL,
  `us_estado` INT(11) NOT NULL DEFAULT 1 COMMENT '0: Inactivo\n1: Activo\n',
  `us_image` VARCHAR(256) NULL,
  `us_email` VARCHAR(128) NULL,
  `fecha_creacion` DATETIME NULL,
  `rol_id` INT NOT NULL,
  `pers_id` INT NULL,
  PRIMARY KEY (`us_id`),
  UNIQUE INDEX `us_usuario_UNIQUE` (`us_usuario` ASC),
  UNIQUE INDEX `us_email_UNIQUE` (`us_email` ASC),
  INDEX `fk_auth_usuario_auth_rol1_idx` (`rol_id` ASC),
  INDEX `fk_auth_usuario_auth_personal1_idx` (`pers_id` ASC),
  CONSTRAINT `fk_auth_usuario_auth_rol1`
    FOREIGN KEY (`rol_id`)
    REFERENCES `auth_rol` (`rol_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_auth_usuario_auth_personal1`
    FOREIGN KEY (`pers_id`)
    REFERENCES `auth_personal` (`pers_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE TABLE `sys_recurso` (
  `recurso_id` INT NOT NULL AUTO_INCREMENT,
  `recurso_desc` VARCHAR(128) NULL,
  `recurso_uri` VARCHAR(256) NULL,
  `recurso_estado` INT(11) NULL COMMENT '0: Desactivado\n1: Activado',
  `recurso_tipo` INT(11) NULL COMMENT '1: Tipo Menu\n2: tipo Recurso',
  `rec_recurso_id` INT NULL,
  PRIMARY KEY (`recurso_id`),
  INDEX `fk_sys_recurso_sys_recurso_idx` (`rec_recurso_id` ASC),
  CONSTRAINT `fk_sys_recurso_sys_recurso`
    FOREIGN KEY (`rec_recurso_id`)
    REFERENCES `sys_recurso` (`recurso_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE TABLE `sys_rol_recurso` (
  `recurso_id` INT NOT NULL,
  `rol_id` INT NOT NULL,
  `rolrec_permiso` VARCHAR(16) NULL COMMENT 'deny: Denegado allow: permitido',
  `rolrec_estado` VARCHAR(45) NULL DEFAULT '1',
  PRIMARY KEY (`recurso_id`, `rol_id`),
  INDEX `fk_sys_recurso_has_auth_rol_auth_rol1_idx` (`rol_id` ASC),
  INDEX `fk_sys_recurso_has_auth_rol_sys_recurso1_idx` (`recurso_id` ASC),
  CONSTRAINT `fk_sys_recurso_has_auth_rol_sys_recurso1`
    FOREIGN KEY (`recurso_id`)
    REFERENCES `sys_recurso` (`recurso_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sys_recurso_has_auth_rol_auth_rol1`
    FOREIGN KEY (`rol_id`)
    REFERENCES `auth_rol` (`rol_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE VIEW `vauth_usuario_login` AS
select t1.us_id,t1.us_usuario,us_password,us_nombre,us_apellidos, 
us_image,us_email,t2.rol_id,t2.rol_desc,
t3.pers_id,t3.empcod,percod,codigo
from auth_usuario t1
inner join auth_rol t2 on t1.rol_id = t2.rol_id
inner join auth_personal t3 on t1.pers_id = t3.pers_id;

alter table sys_recurso add column recurso_orden INT(11) NULL;

